config/routes.rb
Rails.application.routes.draw do
  # devise_for :admin, controllers: { sessions: 'admin/sessions' }
  devise_for :admins, path: 'admins', controllers: { sessions: 'admins/sessions', invitations: 'admins/invitations' }
  devise_for :users, skip: :registrations, controllers: { sessions: 'users/sessions' }

  # You can have the root of your site routed with "root"
  root to: 'dashboards#index'

  namespace 'admins' do
    get 'dashboard', to: 'dashboards#index'
    resources :users
    resources :customers
    resources :car_models
    resources :vehicles
    resources :invoices
  end

  get 'dashboard', to: 'dashboards#index'

  get "layoutsoptions/index"
  get "layoutsoptions/off_canvas"
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  TYPES = %W(Sedan Hybrid 4WD SUV Coupe Convertible Limousine Pickup Luxury Microcar Truck)
  belongs_to :customer
  belongs_to :car_model

  validates :registration_number, presence: true
end

app/controllers/admins/vehicles_controller.rb
module Admins
  class VehiclesController < Admins::AdminsController
    before_action :set_vehicle, only: [:show, :edit, :update, :destroy]

    # GET /vehicles
    # GET /vehicles.json
    def index
      @vehicles = Vehicle.all
    end

    # GET /vehicles/1
    # GET /vehicles/1.json
    def show
    end

    # GET /vehicles/new
    def new
      @vehicle = Vehicle.new
    end

    # GET /vehicles/1/edit
    def edit
    end

    # POST /vehicles
    # POST /vehicles.json
    def create
      @vehicle = Vehicle.new(vehicle_params)

      respond_to do |format|
        if @vehicle.save
          format.html { redirect_to admins_vehicle_path(@vehicle), notice: 'Vehicle was successfully created.' }
          format.json { render :show, status: :created, location: admins_vehicle_path(@vehicle) }
        else
          format.html { render :new }
          format.json { render json: @vehicle.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /vehicles/1
    # PATCH/PUT /vehicles/1.json
    def update
      respond_to do |format|
        if @vehicle.update(vehicle_params)
          format.html { redirect_to admins_vehicle_path(@vehicle), notice: 'Vehicle was successfully updated.' }
          format.json { render :show, status: :ok, location: admins_vehicle_path(@vehicle) }
        else
          format.html { render :edit }
          format.json { render json: @vehicle.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /vehicles/1
    # DELETE /vehicles/1.json
    def destroy
      @vehicle.destroy
      respond_to do |format|
        format.html { redirect_to admins_vehicles_url, notice: 'Vehicle was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_vehicle
        @vehicle = Vehicle.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def vehicle_params
        params.require(:vehicle).permit(:model_year, :model_type, :registration_number, :vin, :color, :technician, :fuel_level, :nogears, :key_number, :enginesize, :engine_number, :gearbox_number, :odometerreading, :price, :customer_id, :car_model_id)
      end
  end
end

app/views/admins/vehicles/_form.html.haml
-# frozen_string_literal: true
= simple_form_for([:admins, @vehicle], wrapper: :horizontal_form,  html: { novalidate: false, class: 'form-horizontal needs-validation form-group' }) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :model_type, as: :radio_buttons, collection: Vehicle::TYPES.zip(Vehicle::TYPES), label_method: :second, value_method: :first, input_html: { class: '' }
    .row
      .col-xs-12.col-md-6
        = f.association :customer, input_html: { class: 'select2' }
        = f.association :car_model, input_html: { class: 'select2' }
        = f.input :registration_number, label: 'Registration#'
      .col-xs-12.col-md-6
        = f.input :model_year
        = f.input :vin
        = f.input :fuel_level
    .row
      .col-xs-12.col-md-6
        = f.input :color
        = f.input :technician
        = f.input :nogears
      .col-xs-12.col-md-6
        = f.input :key_number
        = f.input :enginesize
        = f.input :engine_number
    .row
      .col-xs-12.col-md-6
        = f.input :gearbox_number
        = f.input :odometerreading
        = f.input :price
      .col-xs-12.col-md-6
        = f.input :registration_date, as: :date_time_picker, input_html: { class: '' }
        = f.input :alert_date, as: :date_time_picker, input_html: { class: '' }

  .form-group.row
    .col-sm-4.col-sm-offset-2
      %button.btn.btn-white.btn-sm{type: "submit"} Cancel
      = f.button :submit, class: 'btn btn-primary btn-sm'

app/views/admins/vehicles/edit.html.haml
.wrapper.wrapper-content.animated.fadeInRight
  .row
    .col-lg-12
      .ibox
        .ibox-title
          %h5
            Editing vehicle
            %small update a vehicle.
          .ibox-tools
            %a.collapse-link
              %i.fa.fa-chevron-up
            %a.close-link
              %i.fa.fa-times
          .hr-line-dashed
        .ibox-content
          = render 'form'

          = link_to 'Show', admins_vehicle_path(@vehicle)
          \|
          = link_to 'Back', admins_vehicles_path

app/views/admins/vehicles/index.html.haml
.wrapper.wrapper-content.animated.fadeInRight
  .row
    .col-lg-12
      .ibox
        .ibox-title
          %h5 Listing vehicles
          .ibox-tools
            %a.collapse-link
              %i.fa.fa-chevron-up
            %a.close-link
              %i.fa.fa-times
          = link_to new_admins_vehicle_path, class: 'btn btn-primary btn-outline' do
            %i.fa.fa-plus
            New vehicles
        .ibox-content
          .table-responsive
            %table.table.table-striped.table-bordered.table-hover.dataTables-users
              %thead
                %tr
                  %th Customer
                  %th Car model
                  %th Registration number
                  %th Model year
                  %th Model type
                  %th Nogears
                  %th Key number
                  %th Enginesize
                  %th Engine number
                  %th Gearbox number
                  %th Odometerreading
                  %th Price
                  %th
                  %th
                  %th

              %tbody
                - @vehicles.each do |vehicle|
                  %tr
                    %td= vehicle.customer.name
                    %td= vehicle.car_model.name
                    %td= vehicle.registration_number
                    %td= vehicle.model_year
                    %td= vehicle.model_type
                    %td= vehicle.nogears
                    %td= vehicle.key_number
                    %td= vehicle.enginesize
                    %td= vehicle.engine_number
                    %td= vehicle.gearbox_number
                    %td= vehicle.odometerreading
                    %td= vehicle.price
                    %td= link_to 'Show', admins_vehicle_path(vehicle)
                    %td= link_to 'Edit', edit_admins_vehicle_path(vehicle)
                    %td= link_to 'Destroy', admins_vehicle_path(vehicle), method: :delete, data: { confirm: 'Are you sure?' }

app/views/admins/vehicles/new.html.haml
.wrapper.wrapper-content.animated.fadeInRight
  .row
    .col-lg-12
      .ibox
        .ibox-title
          %h5
            New vehicle
            %small Create a vehicle.
          .ibox-tools
            %a.collapse-link
              %i.fa.fa-chevron-up
            %a.close-link
              %i.fa.fa-times
          .hr-line-dashed
        .ibox-content
          = render 'form'

          = link_to 'Back', admins_vehicles_path

app/views/admins/vehicles/show.html.haml
.wrapper.wrapper-content.animated.fadeInRight
  .row.m-b-lg.m-t-lg
    .col-md-6
      .profile-image
        = image_tag 'garage.png', class: 'rounded-circle circle-border m-b-md'
      .profile-info
        %div
          %div
            %h2.no-margins
              = @vehicle.car_model.name
              = @vehicle.car_model.version
            %h4 Founder of Groupeq
            %small
              There are many variations of passages of Lorem Ipsum available, but the majority
              have suffered alteration in some form Ipsum available.
    .col-md-12
      %p
        %b Customer:
        = @vehicle.customer.name
      %p
        %b Car model:
        = @vehicle.car_model.name
      %p
        %b Model year:
        = @vehicle.model_year
      %p
        %b Model type:
        = @vehicle.model_type
      %p
        %b Registration number:
        = @vehicle.registration_number
      %p
        %b Nogears:
        = @vehicle.nogears
      %p
        %b Key number:
        = @vehicle.key_number
      %p
        %b Enginesize:
        = @vehicle.enginesize
      %p
        %b Engine number:
        = @vehicle.engine_number
      %p
        %b Gearbox number:
        = @vehicle.gearbox_number
      %p
        %b Odometerreading:
        = @vehicle.odometerreading
      %p
        %b Price:
        = @vehicle.price

      = link_to 'Edit', edit_admins_vehicle_path(@vehicle)
      \|
      = link_to 'Back', admins_vehicles_path