config/routes.rb
Rails.application.routes.draw do
  # devise_for :admin, controllers: { sessions: 'admin/sessions' }
  devise_for :admins, path: 'admins', controllers: { sessions: 'admins/sessions', invitations: 'admins/invitations' }
  devise_for :users, skip: :registrations, controllers: { sessions: 'users/sessions' }

  # You can have the root of your site routed with "root"
  root to: 'dashboards#index'

  namespace 'admins' do
    get 'dashboard', to: 'dashboards#index'
    resources :users
    resources :customers
    resources :car_models
    resources :vehicles
    resources :invoices
  end

  get 'dashboard', to: 'dashboards#index'

  get "layoutsoptions/index"
  get "layoutsoptions/off_canvas"
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :skip_password_validation, :skip_en_name_validation

  devise :invitable, :database_authenticatable, :recoverable, :rememberable, :validatable, :confirmable, :lockable, :trackable

  ROLES = %w(representer sport_representer)

  validates :given_name, :family_name, :given_name_kh, :family_name_kh, :email, presence: true
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }
  validate  :validate_role

  def full_name
    if family_name_kh.present? && given_name_kh.present?
      "#{family_name_kh} #{given_name_kh}"
    else
      "#{family_name} #{given_name}"
    end
  end

  protected
    def skip_en_name_validation?
      return false if skip_en_name_validation
      true
    end

    def password_required?
      return false if skip_password_validation
      super
    end

  private

    def validate_role
      if !persisted? && !role.present?
        errors.add(:role, 'must selected')
      end
    end
end

app/controllers/admins/users_controller.rb
module Admins
  class UsersController < Admins::AdminsController
    before_action :find_user, only: [:show, :edit, :update, :destroy]

    def index
      respond_to do |f|
        f.html do
          @users = User.all
        end
        f.json { render json: User.all }
      end
    end

    def new
      @user = User.new
    end

    def create
      @user = User.new(user_params)
      if @user.save
        redirect_to admins_users_path, notice: t('.successfully_created')
      else
        render :new
      end
    end

    def show
    end

    def edit
    end

    def update
      if @user.update_attributes(user_params)
        redirect_to admins_user_path(@user), notice: t('.successfully_updated')
      else
        render :edit
      end
    end

    def destroy
      if @user.destroy
        redirect_to admins_users_url, notice: t('.successfully_deleted')
      else
        redirect_to admins_users_url, alert: t('.alert')
      end
    end

    private

      def user_params
        params.require(:user).permit(:given_name_kh, :family_name_kh, :given_name, :family_name, :email, :role, :title, :phone, :password, :password_confirmation)
      end

      def find_user
        @user = User.find(params[:id])
      end
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  include Accessible
  skip_before_action :check_user, only: :destroy
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/users_controller.rb
module Users
  class UsersController < ::ApplicationController
    before_action :authenticate_user!

  end
end

app/views/users/shared/_error_messages.html.haml
- if resource.errors.any?
  #error_explanation
    %h2
      = I18n.t("errors.messages.not_saved", count: resource.errors.count, resource: resource.class.model_name.human.downcase)
    %ul
      - resource.errors.full_messages.each do |message|
        %li= message

app/views/users/shared/_links.html.haml
- if controller_name != 'sessions'
  %small= link_to t(".sign_in"), new_session_path(resource_name)
  %br/
- if devise_mapping.registerable? && controller_name != 'registrations'
  %p.text-muted.text-center
    %small Do not have an account?
  = link_to t(".sign_up"), new_registration_path(resource_name), class: 'btn btn-sm btn-white btn-block'
  %br/
- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations'
  = link_to new_password_path(resource_name) do
    %small= t(".forgot_your_password")
  %br/
- if devise_mapping.confirmable? && controller_name != 'confirmations'
  = link_to t('.didn_t_receive_confirmation_instructions'), new_confirmation_path(resource_name)
  %br/
- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks'
  = link_to t('.didn_t_receive_unlock_instructions'), new_unlock_path(resource_name)
  %br/
- if devise_mapping.omniauthable?
  - resource_class.omniauth_providers.each do |provider|
    = link_to t('.sign_in_with_provider', provider: OmniAuth::Utils.camelize(provider)), omniauth_authorize_path(resource_name, provider)
    %br/