config/routes.rb
Rails.application.routes.draw do
  # devise_for :admin, controllers: { sessions: 'admin/sessions' }
  devise_for :admins, path: 'admins', controllers: { sessions: 'admins/sessions', invitations: 'admins/invitations' }
  devise_for :users, skip: :registrations, controllers: { sessions: 'users/sessions' }

  # You can have the root of your site routed with "root"
  root to: 'dashboards#index'

  namespace 'admins' do
    get 'dashboard', to: 'dashboards#index'
    resources :users
    resources :customers
    resources :car_models
    resources :vehicles
    resources :invoices
  end

  get 'dashboard', to: 'dashboards#index'

  get "layoutsoptions/index"
  get "layoutsoptions/off_canvas"
end

app/models/car_model.rb
class CarModel < ApplicationRecord
  belongs_to :parent,           class_name: 'CarModel', optional: true
  has_many :children,           class_name: 'CarModel', foreign_key: 'parent_id', dependent: :destroy
  has_many :vehicles

  validates :name, presence: true

  scope :only_parents,  -> { where(parent_id: nil) }
  scope :only_children, -> { where.not(parent_id: nil) }
  scope :names,         -> { only_children.pluck(:name) }
end

app/controllers/admins/car_models_controller.rb
module Admins
  class CarModelsController < Admins::AdminsController
    before_action :set_model, only: [:show, :edit, :update, :destroy]

    # GET /models
    # GET /models.json
    def index
      @car_models = CarModel.only_children
    end

    # GET /models/1
    # GET /models/1.json
    def show
    end

    # GET /models/new
    def new
      @car_model = CarModel.new
    end

    # GET /models/1/edit
    def edit
    end

    # POST /models
    # POST /models.json
    def create
      @car_model = CarModel.new(model_params)

      respond_to do |format|
        if @car_model.save
          format.html { redirect_to admins_car_model_path(@car_model), notice: 'CarModel was successfully created.' }
          format.json { render :show, status: :created, location: admins_car_model_path(@car_model) }
        else
          format.html { render :new }
          format.json { render json: @car_model.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /models/1
    # PATCH/PUT /models/1.json
    def update
      respond_to do |format|
        if @car_model.update(model_params)
          format.html { redirect_to admins_car_model_path(@car_model), notice: 'Car model was successfully updated.' }
          format.json { render :show, status: :ok, location: admins_car_model_path(@car_model) }
        else
          format.html { render :edit }
          format.json { render json: @car_model.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /models/1
    # DELETE /models/1.json
    def destroy
      @car_model.destroy
      respond_to do |format|
        format.html { redirect_to admins_car_models_url, notice: 'Car model was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_model
        @car_model = CarModel.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def model_params
        params.require(:car_model).permit(:name, :version, :parent_id)
      end
  end
end

app/views/admins/car_models/_form.html.haml
-# frozen_string_literal: true
= simple_form_for([:admins, @car_model], wrapper: :horizontal_form,  html: { novalidate: false, class: 'form-horizontal needs-validation form-group' }) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .form-inputs
    = f.input :name
    = f.input :version
    = f.input :parent_id, collection: CarModel.only_parents.map{ |car_model| [car_model.name.titleize, car_model.id] }, input_html: { class: 'select2' }

  .form-group.row
    .col-sm-4.col-sm-offset-2
      %button.btn.btn-white.btn-sm{:type => "submit"} Cancel
      = f.button :submit, class: 'btn btn-primary btn-sm'

app/views/admins/car_models/edit.html.haml
.wrapper.wrapper-content.animated.fadeInRight
  .row
    .col-lg-12
      .ibox
        .ibox-title
          %h5
            Editing car model
            %small update a car model.
          .ibox-tools
            %a.collapse-link
              %i.fa.fa-chevron-up
            %a.close-link
              %i.fa.fa-times
          .hr-line-dashed
        .ibox-content
          = render 'form'

          = link_to 'Show', admins_car_model_path(@car_model)
          \|
          = link_to 'Back', admins_car_models_path

app/views/admins/car_models/index.html.haml
.wrapper.wrapper-content.animated.fadeInRight
  .row
    .col-lg-12
      .ibox
        .ibox-title
          %h5 Listing cars' models
          .ibox-tools
            %a.collapse-link
              %i.fa.fa-chevron-up
            %a.close-link
              %i.fa.fa-times
          = link_to new_admins_car_model_path, class: 'btn btn-primary btn-outline' do
            %i.fa.fa-plus
            New Model
        .ibox-content
          .table-responsive
            %table.table.table-striped.table-bordered.table-hover.dataTables-users
              %thead
                %tr
                  %th Name
                  %th Version
                  %th Model
                  %th
                  %th
                  %th

              %tbody
                - @car_models.each do |car_model|
                  %tr
                    %td= car_model.name
                    %td= car_model.version
                    %td= car_model.parent_id
                    %td= link_to 'Show', admins_car_model_path(car_model)
                    %td= link_to 'Edit', edit_admins_car_model_path(car_model)
                    %td= link_to 'Destroy', admins_car_model_path(car_model), method: :delete, data: { confirm: 'Are you sure?' }

app/views/admins/car_models/new.html.haml
.wrapper.wrapper-content.animated.fadeInRight
  .row
    .col-lg-12
      .ibox
        .ibox-title
          %h5
            New car model
            %small Create a car model.
          .ibox-tools
            %a.collapse-link
              %i.fa.fa-chevron-up
            %a.close-link
              %i.fa.fa-times
          .hr-line-dashed
        .ibox-content
          = render 'form'

          = link_to 'Back', admins_car_models_path

app/views/admins/car_models/show.html.haml
.wrapper.wrapper-content.animated.fadeInRight
  .row.m-b-lg.m-t-lg
    .col-md-6
      .profile-image
        = image_tag 'garage.png', class: 'rounded-circle circle-border m-b-md'
      .profile-info
        %div
          %div
            %h2.no-margins
              = @car_model.name
            %h4 Founder of Groupeq
            %small
              There are many variations of passages of Lorem Ipsum available, but the majority
              have suffered alteration in some form Ipsum available.
    .col-md-12
      %p
        %b Version:
        = @car_model.version
      %p
        %b Parent:
        = @car_model.parent_id

      = link_to 'Edit', edit_admins_car_model_path(@car_model)
      \|
      = link_to 'Back', admins_car_models_path