config/routes.rb
Rails.application.routes.draw do
  # devise_for :admin, controllers: { sessions: 'admin/sessions' }
  devise_for :admins, path: 'admins', controllers: { sessions: 'admins/sessions', invitations: 'admins/invitations' }
  devise_for :users, skip: :registrations, controllers: { sessions: 'users/sessions' }

  # You can have the root of your site routed with "root"
  root to: 'dashboards#index'

  namespace 'admins' do
    get 'dashboard', to: 'dashboards#index'
    resources :users
    resources :customers
    resources :car_models
    resources :vehicles
    resources :invoices
  end

  get 'dashboard', to: 'dashboards#index'

  get "layoutsoptions/index"
  get "layoutsoptions/off_canvas"
end

app/models/invoice.rb
class Invoice < ApplicationRecord
  belongs_to :user
  belongs_to :customer
end

app/controllers/admins/invoices_controller.rb
module Admins
  class InvoicesController < Admins::AdminsController
    before_action :set_invoice, only: [:show, :edit, :update, :destroy]

    # GET /invoices
    # GET /invoices.json
    def index
      @invoices = Invoice.all
    end

    # GET /invoices/1
    # GET /invoices/1.json
    def show
    end

    # GET /invoices/new
    def new
      @invoice = Invoice.new
    end

    # GET /invoices/1/edit
    def edit
    end

    # POST /invoices
    # POST /invoices.json
    def create
      @invoice = Invoice.new(invoice_params)

      respond_to do |format|
        if @invoice.save
          format.html { redirect_to admins_invoice_path(@invoice), notice: 'Invoice was successfully created.' }
          format.json { render :show, status: :created, location: admins_invoice_path(@invoice) }
        else
          format.html { render :new }
          format.json { render json: @invoice.errors, status: :unprocessable_entity }
        end
      end
    end

    # PATCH/PUT /invoices/1
    # PATCH/PUT /invoices/1.json
    def update
      respond_to do |format|
        if @invoice.update(invoice_params)
          format.html { redirect_to admins_invoice_path(@invoice), notice: 'Invoice was successfully updated.' }
          format.json { render :show, status: :ok, location: admins_invoice_path(@invoice) }
        else
          format.html { render :edit }
          format.json { render json: @invoice.errors, status: :unprocessable_entity }
        end
      end
    end

    # DELETE /invoices/1
    # DELETE /invoices/1.json
    def destroy
      @invoice.destroy
      respond_to do |format|
        format.html { redirect_to admins_invoices_url, notice: 'Invoice was successfully destroyed.' }
        format.json { head :no_content }
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_invoice
        @invoice = Invoice.find(params[:id])
      end

      # Never trust parameters from the scary internet, only allow the white list through.
      def invoice_params
        params.require(:invoice).permit(:reference_number, :original_price, :earning_value, :total_price, :discount_price, :deposit_price, :balance, :user_id, :customer_id)
      end
  end
end

app/views/admins/invoices/_form.html.haml
-# frozen_string_literal: true
= simple_form_for([:admins, @invoice],  html: { novalidate: false, class: 'form-horizontal needs-validation form-group' }) do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  .row
    .col-md-6
      %fieldset.card.card-body.bg-light.border.p-2
        %legend.w-auto
          %h4 Customer Vehicle Details
        = f.input :reference_number, readonly: true, input_html: { value: "#{Invoice.count + 1000}".rjust(7, '0') }
        .row.form-group
          .col-3
            = f.label :customer
          .col-6
            = f.association :customer, label: false, wrapper: false, input_html: { class: 'select2' }
          .col-3
            .text-center
              %button.btn.btn-primary{"data-target" => "#form-customer", "data-toggle" => "modal", :type => "button"}
                Add Customer
        .row.form-group
          %label.form-control-label.float.optional.col-sm-3 Comapany name:
          .col-sm-9
            = text_field_tag :compay, nil, class: 'form-control'
        .row.form-group
          %label.form-control-label.float.optional.col-sm-3 Email:
          .col-sm-9
            = text_field_tag :email, nil, class: 'form-control'
        .row.form-group
          %label.form-control-label.float.optional.col-sm-3 Phone1:
          .col-sm-9
            = text_field_tag :phone1, nil, class: 'form-control'
        .row.form-group
          %label.form-control-label.float.optional.col-sm-3 Phone2:
          .col-sm-9
            = text_field_tag :phone2, nil, class: 'form-control'
        .row.form-group
          %label.form-control-label.float.optional.col-sm-3 Address:
          .col-sm-9
            = text_field_tag :address, nil, class: 'form-control'
        %hr.hr-line-dashed/
        .row
          .col-6
            .row.form-group
              %label.form-control-label.float.optional.col-sm-3 Registration:
              .col-sm-9
                = text_field_tag :registration_number, nil, class: 'form-control'
          .col-6
            .row.form-group
              %label.form-control-label.float.optional.col-sm-3 Year:
              .col-sm-9
                = text_field_tag :model_year, nil, class: 'form-control'
        .row
          .col-6
            .row.form-group
              %label.form-control-label.float.optional.col-sm-3 Car Model:
              .col-sm-9
                = text_field_tag :model_id, nil, class: 'form-control'
          .col-6
            .row.form-group
              .col-sm-12
                = text_field_tag :model_year_info, nil, class: 'form-control'
        .row
          .col-6
            .row.form-group
              %label.form-control-label.float.optional.col-sm-3 VIN:
              .col-sm-9
                = text_field_tag :vin, nil, class: 'form-control'
          .col-6
            .row.form-group
              %label.form-control-label.float.optional.col-sm-3 Engine #:
              .col-sm-9
                = text_field_tag :engine_number, nil, class: 'form-control'
        .row
          .col-6
            .row.form-group
              %label.form-control-label.float.optional.col-sm-3 Fuel level:
              .col-sm-9
                = text_field_tag :fuel_level, nil, class: 'form-control'
          .col-6
            .row.form-group
              %label.form-control-label.float.optional.col-sm-3 Color:
              .col-sm-9
                = text_field_tag :color, nil, class: 'form-control'
        .row
          .col-6
            .row.form-group
              %label.form-control-label.float.optional.col-sm-3 Technician:
              .col-sm-9
                = text_field_tag :technician, nil, class: 'form-control'
          .col-6
            .row.form-group
              %label.form-control-label.float.optional.col-sm-3 Reg Date:
              .col-sm-9
                = text_field_tag :registration_date, nil, class: 'form-control'
        .row
          .col-6
            .row.form-group
              %label.form-control-label.float.optional.col-sm-3 Odometer#:
              .col-sm-9
                = text_field_tag :odometerreading, nil, class: 'form-control'
          .col-6
            .row.form-group
              %label.form-control-label.float.optional.col-sm-3.text-success.font-weight-bold Reg Date:
              .col-sm-9
                = text_field_tag :alert_date, Date.today.strftime("%d/%m/%Y"), class: 'form-control'
        %hr.hr-line-dashed/
        .card.text-white.bg-warning
          .card-header Additional Repairment
          .card-body
            %h5.card-title Warning card title
            %p.card-text Some quick example text to build on the card title and make up the bulk of the card's content.


    .col-md-6
      .table-responsive.span3
        %h3.text-danger Products Quotation
        %table.table.table-striped.table-bordered.table-hover.dataTables-users
          %thead
            %tr
              %th Code
              %th Name EN
              %th Name KH
              %th QTY
              %th Price
              %th Total
              %th Orin Price


          %tbody
            %tr
              %td
              %td
              %td
              %td
              %td
              %td
              %td
      %hr.hr-line-dashed/
      .table-responsive.span3
        %h3.text-success Repairment / Service list
        %table.table.table-striped.table-bordered.table-hover.dataTables-users
          %thead
            %tr
              %th Code
              %th Name EN
              %th Name KH
              %th QTY
              %th Price
              %th Total
              %th Orin Price


          %tbody
            %tr
              %td
              %td
              %td
              %td
              %td
              %td
              %td


      = f.input :original_price
      = f.input :earning_value
      = f.input :total_price
      = f.input :discount_price
      = f.input :deposit_price
      = f.input :balance
      = f.association :user

  .form-group.row
    .col-sm-4.col-sm-offset-2
      %button.btn.btn-white.btn-sm{type: "submit"} Cancel
      = f.button :submit, class: 'btn btn-primary btn-sm'

= render 'form_customer'

app/views/admins/invoices/_form_customer.haml
#form-customer.modal.inmodal.fade{"aria-hidden" => "true", :role => "dialog", :tabindex => "-1"}
  .modal-dialog.modal-lg
    .modal-content
      .modal-header
        %button.close{"data-dismiss" => "modal", :type => "button"}
          %span{"aria-hidden" => "true"} ×
          %span.sr-only Close
        %h4.modal-title Create new customer
        %small.font-bold Customer will be automatically selected after you created.
      = simple_form_for([:admins, Customer.new], wrapper: :horizontal_form, html: { data: { url: admins_customers_path(format: :json), type: :json }, class: 'form-horizontal needs-validation form-group' }) do |f|
        .modal-body
          .form-inputs
            .row
              .col-xs-12.col-md-6
                = f.input :name, html5: true, required: 'required'
                = f.input :compay
                = f.input :address
              .col-xs-12.col-md-6
                = f.input :email
                = f.input :phone1, html5: true, required: 'required'
                = f.input :phone2
            .row
              .col-12

                %fieldset.card.card-body.bg-light.border.p-2
                  %legend.w-auto
                    %h4 Customer Vehicle Details
                  = f.simple_fields_for :vehicles, wrapper: :horizontal_form do |vf|
                    .row
                      .col-xs-12.col-md-6
                        = vf.hidden_field :customer_id, input_html: { class: 'select2' }
                        = vf.input :car_model_id, collection: CarModel.only_parents, as: :grouped_select, group_method: :children, required: 'required', input_html: { class: 'select2' }
                        = vf.input :registration_number, required: 'required', label: 'Registration#'
                        = vf.input :model_year
                      .col-xs-12.col-md-6
                        = vf.input :vin
                        = vf.input :fuel_level
                        = vf.input :color
                    .row
                      .col-xs-12.col-md-6
                        = vf.input :technician
                        = vf.input :nogears
                        = vf.input :key_number
                      .col-xs-12.col-md-6
                        = vf.input :enginesize
                        = vf.input :engine_number
                        = vf.input :gearbox_number
                    .row
                      .col-xs-12.col-md-6
                        = vf.input :odometerreading
                        = vf.input :price
                      .col-xs-12.col-md-6
                        = vf.input :registration_date, as: :date_time_picker, input_html: { class: '' }
                        = vf.input :alert_date, as: :date_time_picker, input_html: { class: '' }


        .modal-footer
          %button.btn.btn-white{"data-dismiss" => "modal", :type => "button"} Close
          = f.button :submit, class: 'btn btn-primary btn-sm', id: 'create-new-customer'

app/views/admins/invoices/edit.html.haml
.wrapper.wrapper-content.animated.fadeInRight
  .row
    .col-lg-12
      .ibox
        .ibox-title
          %h5
            Editing invoice
            %small update an invoice.
          .ibox-tools
            %a.collapse-link
              %i.fa.fa-chevron-up
            %a.close-link
              %i.fa.fa-times
          .hr-line-dashed
        .ibox-content
          = render 'form'

          = link_to 'Show', @invoice
          \|
          = link_to 'Back', admins_invoices_path

app/views/admins/invoices/index.html.haml
.wrapper.wrapper-content.animated.fadeInRight
  .row
    .col-lg-12
      .ibox
        .ibox-title
          %h5 Listing invoices
          .ibox-tools
            %a.collapse-link
              %i.fa.fa-chevron-up
            %a.close-link
              %i.fa.fa-times
          = link_to new_admins_invoice_path, class: 'btn btn-primary btn-outline' do
            %i.fa.fa-plus
            New Invoice
        .ibox-content
          .table-responsive
            %table.table.table-striped.table-bordered.table-hover.dataTables-users
              %thead
                %tr
                  %th Reference number
                  %th Original price
                  %th Earning value
                  %th Total price
                  %th Discount price
                  %th Deposit price
                  %th Balance
                  %th User
                  %th Customer
                  %th
                  %th
                  %th

              %tbody
                - @invoices.each do |invoice|
                  %tr
                    %td= invoice.reference_number
                    %td= invoice.original_price
                    %td= invoice.earning_value
                    %td= invoice.total_price
                    %td= invoice.discount_price
                    %td= invoice.deposit_price
                    %td= invoice.balance
                    %td= invoice.user.full_name
                    %td= invoice.customer.name
                    %td= link_to 'Show', admins_invoice_path(invoice)
                    %td= link_to 'Edit', edit_admins_invoice_path(invoice)
                    %td= link_to 'Destroy', admins_invoice_path(invoice), method: :delete, data: { confirm: 'Are you sure?' }

app/views/admins/invoices/new.html.haml
.wrapper.wrapper-content.animated.fadeInRight
  .row
    .col-lg-12
      .ibox
        .ibox-title
          %h5
            New invoice
            %small Create a an invoice.
          .ibox-tools
            %a.collapse-link
              %i.fa.fa-chevron-up
            %a.close-link
              %i.fa.fa-times
          .hr-line-dashed
        .ibox-content
          = render 'form'

          = link_to 'Back', admins_invoices_path

app/views/admins/invoices/show.html.haml
wrapper.wrapper-content.animated.fadeInRight
  .row.m-b-lg.m-t-lg
    .col-md-6
      .profile-image
        = image_tag 'garage.png', class: 'rounded-circle circle-border m-b-md'
      .profile-info
        %div
          %div
            %h2.no-margins
              %p
                %b Reference number:
                = @invoice.reference_number
            %h4 Founder of Groupeq
            %small
              There are many variations of passages of Lorem Ipsum available, but the majority
              have suffered alteration in some form Ipsum available.
    .col-md-12
      %p
        %b Original price:
        = @invoice.original_price
      %p
        %b Earning value:
        = @invoice.earning_value
      %p
        %b Total price:
        = @invoice.total_price
      %p
        %b Discount price:
        = @invoice.discount_price
      %p
        %b Deposit price:
        = @invoice.deposit_price
      %p
        %b Balance:
        = @invoice.balance
      %p
        %b User:
        = @invoice.user
      %p
        %b Customer:
        = @invoice.customer

      = link_to 'Edit', edit_admins_invoice_path(@invoice)
      \|
      = link_to 'Back', admins_invoices_path